### ISSUE TITLE
Minor visibility issues with "Not Allowed"-signs

### ISSUE THREAD

**Issue by idarob** [zrax/cctools#13]
* Empty no-signs are not visible under canopies
* No-signs are displayed on top of blocks (preferably the block would become transparent instead. If an item is below the no-sign, the block becomes transparent but the no-sign is still on top. In-game the no signs are not visible under dirt or ice blocks.)

**Comment by idarob** [comment]
This might already be fixed for the next release?

**Comment by zrax** [comment]
Yeah, both of these should already be fixed for the next release.
